image: maven:3-jdk-8
# These are the default stages.
# You don't need to explicitly define them.
# But you could define any stages you want.
stages:
  - deploy
    
pages:
  stage: deploy
  script:
  - cd docs
  - mkdir html
  - mkdir html/xerleben
  - java -jar widoco.jar -ontFile ../XErleben/xerleben2_1.ttl_mod.ttl -outFolder html/xerleben/ -rewriteAll -webVowl -confFile config/xerleben.properties
  - mkdir html/xplanung
  - java -jar widoco.jar -ontFile ../XPlanung/xplanung5_0.ttl -outFolder html/xplanung/ -rewriteAll -webVowl -confFile config/xplanung.properties
  - mkdir html/xkat
  - java -jar widoco.jar -ontFile ../XKatastrophenhilfe/xkat1_1.ttl -outFolder html/xkat/ -rewriteAll -webVowl -confFile config/xkat.properties
  - mkdir html/aaa
  - java -jar widoco.jar -ontFile ../AAA-Data/aaa6.ttl -outFolder html/aaa/ -rewriteAll -webVowl -confFile config/aaa.properties
  - mv index.html html/index.html
  - mv html ../public 
  artifacts:
    paths:
    - public
  only:
  - master
