image: maven:3-jdk-8
# These are the default stages.
# You don't need to explicitly define them.
# But you could define any stages you want.
stages:
  - deploy
    
pages:
  stage: deploy
  script:
  - cd docs
  - mkdir html
  - mkdir html/xerleben
  - java -jar widoco.jar -ontFile ../XErleben/xerleben2_1.ttl_mod.ttl -outFolder html/xerleben/ -getOntologyMetadata -rewriteAll -webVowl -confFile config/config.properties
  - mv html ../public 
  artifacts:
    paths:
    - public
  only:
  - master
