image: maven:3-jdk-8
# These are the default stages.
# You don't need to explicitly define them.
# But you could define any stages you want.
stages:
  - deploy
    
pages:
  stage: deploy
  script:
  - cd docs
  - java -jar widoco.jar -ontFile XErleben/xerleben -outFolder html/xerleben/ -getOntologyMetadata -rewriteAll -crossRef -en -webVowl
  - mv html ../public 
  artifacts:
    paths:
    - public
  only:
  - master
